version: "2"

services:
 minetest:
  image: ghcr.io/minetest/minetest:5.10.0
  restart: always
  user: root
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./game:/root/.minetest/worlds/world/game"
   - "./worldmods:/root/.minetest/worlds/world/worldmods"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
   - "./minetest.conf:/minetest.conf"
  ports:
    - "30001:30001/udp"
  networks:
   - terminator
   - default
  entrypoint: ["--config", "/minetest.conf"]

 matterbridge:
   image: 42wim/matterbridge:1.26.0
   dns:
    - 8.8.4.4
    - 8.8.8.8
   volumes:
    - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml
    - ./remotenickformat.tengo:/remotenickformat.tengo

 mesecons-lab-ui:
  image: ghcr.io/minetest-go/mtui:v1.78
  networks:
   - terminator
   - default
  environment:
   COOKIE_DOMAIN: "meseconslab.luanti.ch"
   COOKIE_SECURE: "true"
   WORLD_DIR: "/root/.minetest/worlds/world"
   API_KEY: "{{mtui_key}}"
   ENABLE_FEATURES: "shell,luashell,monitoring"
   SERVER_NAME: "Mesecons lab"
  volumes:
   - "./data/world:/root/.minetest/worlds/world"
   - "./world.mt:/root/.minetest/worlds/world/world.mt"
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.meseconslab-luanti-ch.rule=Host(`meseconslab.luanti.ch`)"
    - "traefik.http.services.meseconslab-luanti-ch.loadbalancer.server.port=8080"
    - "traefik.http.routers.meseconslab-luanti-ch.entrypoints=websecure"
    - "traefik.http.routers.meseconslab-luanti-ch.tls.certresolver=default"

 meseconslab-redirect:
  image: nginx:1.25.2
  networks:
   - terminator
   - default
  restart: always
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.meseconslab-minetest-ch.rule=Host(`meseconslab.minetest.ch`)"
    - "traefik.http.services.meseconslab-minetest-ch.loadbalancer.server.port=80"
    - "traefik.http.routers.meseconslab-minetest-ch.entrypoints=websecure"
    - "traefik.http.routers.meseconslab-minetest-ch.tls.certresolver=default"
  volumes:
   - "./redirect.conf:/etc/nginx/conf.d/default.conf:ro"

networks:
 terminator:
  external: true
